# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: peptides.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


import raw_proteins_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='peptides.proto',
  package='pb',
  serialized_pb='\n\x0epeptides.proto\x12\x02pb\x1a\x12raw_proteins.proto\"+\n\x08Location\x12\x12\n\nprotein_id\x18\x01 \x01(\x05\x12\x0b\n\x03pos\x18\x02 \x01(\x05\"\x8f\x02\n\x07Peptide\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04mass\x18\x02 \x01(\x01\x12\x0e\n\x06length\x18\x03 \x01(\x05\x12$\n\x0e\x66irst_location\x18\x04 \x01(\x0b\x32\x0c.pb.Location\x12\x11\n\x05peak1\x18\x05 \x03(\x05\x42\x02\x10\x01\x12\x11\n\x05peak2\x18\x06 \x03(\x05\x42\x02\x10\x01\x12\x15\n\tneg_peak1\x18\x07 \x03(\x05\x42\x02\x10\x01\x12\x15\n\tneg_peak2\x18\x08 \x03(\x05\x42\x02\x10\x01\x12\x19\n\rmodifications\x18\t \x03(\x05\x42\x02\x10\x01\x12\x1b\n\x13\x61ux_locations_index\x18\n \x01(\x05\x12\x10\n\x08is_decoy\x18\x0b \x01(\x08\"\x16\n\x06Series\x12\x05\n\x01Y\x10\x00\x12\x05\n\x01\x42\x10\x01\"-\n\x0b\x41uxLocation\x12\x1e\n\x08location\x18\x01 \x03(\x0b\x32\x0c.pb.LocationB\x02H\x01')



_PEPTIDE_SERIES = _descriptor.EnumDescriptor(
  name='Series',
  full_name='pb.Peptide.Series',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Y', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='B', index=1, number=1,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=337,
  serialized_end=359,
)


_LOCATION = _descriptor.Descriptor(
  name='Location',
  full_name='pb.Location',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='protein_id', full_name='pb.Location.protein_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos', full_name='pb.Location.pos', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=42,
  serialized_end=85,
)


_PEPTIDE = _descriptor.Descriptor(
  name='Peptide',
  full_name='pb.Peptide',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pb.Peptide.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mass', full_name='pb.Peptide.mass', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='length', full_name='pb.Peptide.length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='first_location', full_name='pb.Peptide.first_location', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peak1', full_name='pb.Peptide.peak1', index=4,
      number=5, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='peak2', full_name='pb.Peptide.peak2', index=5,
      number=6, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='neg_peak1', full_name='pb.Peptide.neg_peak1', index=6,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='neg_peak2', full_name='pb.Peptide.neg_peak2', index=7,
      number=8, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='modifications', full_name='pb.Peptide.modifications', index=8,
      number=9, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='aux_locations_index', full_name='pb.Peptide.aux_locations_index', index=9,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='is_decoy', full_name='pb.Peptide.is_decoy', index=10,
      number=11, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _PEPTIDE_SERIES,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=88,
  serialized_end=359,
)


_AUXLOCATION = _descriptor.Descriptor(
  name='AuxLocation',
  full_name='pb.AuxLocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='location', full_name='pb.AuxLocation.location', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=361,
  serialized_end=406,
)

_PEPTIDE.fields_by_name['first_location'].message_type = _LOCATION
_PEPTIDE_SERIES.containing_type = _PEPTIDE;
_AUXLOCATION.fields_by_name['location'].message_type = _LOCATION
DESCRIPTOR.message_types_by_name['Location'] = _LOCATION
DESCRIPTOR.message_types_by_name['Peptide'] = _PEPTIDE
DESCRIPTOR.message_types_by_name['AuxLocation'] = _AUXLOCATION

class Location(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _LOCATION

  # @@protoc_insertion_point(class_scope:pb.Location)

class Peptide(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _PEPTIDE

  # @@protoc_insertion_point(class_scope:pb.Peptide)

class AuxLocation(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _AUXLOCATION

  # @@protoc_insertion_point(class_scope:pb.AuxLocation)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\001')
_PEPTIDE.fields_by_name['peak1'].has_options = True
_PEPTIDE.fields_by_name['peak1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PEPTIDE.fields_by_name['peak2'].has_options = True
_PEPTIDE.fields_by_name['peak2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PEPTIDE.fields_by_name['neg_peak1'].has_options = True
_PEPTIDE.fields_by_name['neg_peak1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PEPTIDE.fields_by_name['neg_peak2'].has_options = True
_PEPTIDE.fields_by_name['neg_peak2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_PEPTIDE.fields_by_name['modifications'].has_options = True
_PEPTIDE.fields_by_name['modifications']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
