// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: raw_proteins.proto

#ifndef PROTOBUF_raw_5fproteins_2eproto__INCLUDED
#define PROTOBUF_raw_5fproteins_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pb {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_raw_5fproteins_2eproto();
void protobuf_AssignDesc_raw_5fproteins_2eproto();
void protobuf_ShutdownFile_raw_5fproteins_2eproto();

class Protein;

// ===================================================================

class Protein : public ::google::protobuf::Message {
 public:
  Protein();
  virtual ~Protein();

  Protein(const Protein& from);

  inline Protein& operator=(const Protein& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Protein& default_instance();

  void Swap(Protein* other);

  // implements Message ----------------------------------------------

  Protein* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Protein& from);
  void MergeFrom(const Protein& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string name = 1;
  inline bool has_name() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name() const;
  inline void set_name(const ::std::string& value);
  inline void set_name(const char* value);
  inline void set_name(const char* value, size_t size);
  inline ::std::string* mutable_name();
  inline ::std::string* release_name();
  inline void set_allocated_name(::std::string* name);

  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // optional string residues = 3;
  inline bool has_residues() const;
  inline void clear_residues();
  static const int kResiduesFieldNumber = 3;
  inline const ::std::string& residues() const;
  inline void set_residues(const ::std::string& value);
  inline void set_residues(const char* value);
  inline void set_residues(const char* value, size_t size);
  inline ::std::string* mutable_residues();
  inline ::std::string* release_residues();
  inline void set_allocated_residues(::std::string* residues);

  // optional int32 target_pos = 5;
  inline bool has_target_pos() const;
  inline void clear_target_pos();
  static const int kTargetPosFieldNumber = 5;
  inline ::google::protobuf::int32 target_pos() const;
  inline void set_target_pos(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pb.Protein)
 private:
  inline void set_has_name();
  inline void clear_has_name();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_residues();
  inline void clear_has_residues();
  inline void set_has_target_pos();
  inline void clear_has_target_pos();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* name_;
  ::std::string* residues_;
  ::google::protobuf::int32 id_;
  ::google::protobuf::int32 target_pos_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_raw_5fproteins_2eproto();
  friend void protobuf_AssignDesc_raw_5fproteins_2eproto();
  friend void protobuf_ShutdownFile_raw_5fproteins_2eproto();

  void InitAsDefaultInstance();
  static Protein* default_instance_;
};
// ===================================================================


// ===================================================================

// Protein

// optional string name = 1;
inline bool Protein::has_name() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Protein::set_has_name() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Protein::clear_has_name() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Protein::clear_name() {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    name_->clear();
  }
  clear_has_name();
}
inline const ::std::string& Protein::name() const {
  return *name_;
}
inline void Protein::set_name(const ::std::string& value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Protein::set_name(const char* value) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(value);
}
inline void Protein::set_name(const char* value, size_t size) {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Protein::mutable_name() {
  set_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    name_ = new ::std::string;
  }
  return name_;
}
inline ::std::string* Protein::release_name() {
  clear_has_name();
  if (name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = name_;
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Protein::set_allocated_name(::std::string* name) {
  if (name_ != &::google::protobuf::internal::kEmptyString) {
    delete name_;
  }
  if (name) {
    set_has_name();
    name_ = name;
  } else {
    clear_has_name();
    name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 id = 2;
inline bool Protein::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Protein::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Protein::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Protein::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 Protein::id() const {
  return id_;
}
inline void Protein::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional string residues = 3;
inline bool Protein::has_residues() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Protein::set_has_residues() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Protein::clear_has_residues() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Protein::clear_residues() {
  if (residues_ != &::google::protobuf::internal::kEmptyString) {
    residues_->clear();
  }
  clear_has_residues();
}
inline const ::std::string& Protein::residues() const {
  return *residues_;
}
inline void Protein::set_residues(const ::std::string& value) {
  set_has_residues();
  if (residues_ == &::google::protobuf::internal::kEmptyString) {
    residues_ = new ::std::string;
  }
  residues_->assign(value);
}
inline void Protein::set_residues(const char* value) {
  set_has_residues();
  if (residues_ == &::google::protobuf::internal::kEmptyString) {
    residues_ = new ::std::string;
  }
  residues_->assign(value);
}
inline void Protein::set_residues(const char* value, size_t size) {
  set_has_residues();
  if (residues_ == &::google::protobuf::internal::kEmptyString) {
    residues_ = new ::std::string;
  }
  residues_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* Protein::mutable_residues() {
  set_has_residues();
  if (residues_ == &::google::protobuf::internal::kEmptyString) {
    residues_ = new ::std::string;
  }
  return residues_;
}
inline ::std::string* Protein::release_residues() {
  clear_has_residues();
  if (residues_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = residues_;
    residues_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void Protein::set_allocated_residues(::std::string* residues) {
  if (residues_ != &::google::protobuf::internal::kEmptyString) {
    delete residues_;
  }
  if (residues) {
    set_has_residues();
    residues_ = residues;
  } else {
    clear_has_residues();
    residues_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional int32 target_pos = 5;
inline bool Protein::has_target_pos() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Protein::set_has_target_pos() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Protein::clear_has_target_pos() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Protein::clear_target_pos() {
  target_pos_ = 0;
  clear_has_target_pos();
}
inline ::google::protobuf::int32 Protein::target_pos() const {
  return target_pos_;
}
inline void Protein::set_target_pos(::google::protobuf::int32 value) {
  set_has_target_pos();
  target_pos_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace pb

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_raw_5fproteins_2eproto__INCLUDED
