# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: spectrum.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='spectrum.proto',
  package='pb',
  serialized_pb='\n\x0espectrum.proto\x12\x02pb\"\xd7\x01\n\x08Spectrum\x12\x14\n\x08peak_m_z\x18\x01 \x03(\x03\x42\x02\x10\x01\x12\x1a\n\x0epeak_intensity\x18\x02 \x03(\x03\x42\x02\x10\x01\x12\x1c\n\x14peak_m_z_denominator\x18\x03 \x01(\x05\x12\"\n\x1apeak_intensity_denominator\x18\x04 \x01(\x05\x12\x17\n\x0fspectrum_number\x18\x05 \x01(\x05\x12\x15\n\rprecursor_m_z\x18\x06 \x01(\x01\x12\r\n\x05rtime\x18\x08 \x01(\x01\x12\x18\n\x0c\x63harge_state\x18\x07 \x03(\x05\x42\x02\x10\x01\x42\x02H\x01')




_SPECTRUM = _descriptor.Descriptor(
  name='Spectrum',
  full_name='pb.Spectrum',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='peak_m_z', full_name='pb.Spectrum.peak_m_z', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='peak_intensity', full_name='pb.Spectrum.peak_intensity', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
    _descriptor.FieldDescriptor(
      name='peak_m_z_denominator', full_name='pb.Spectrum.peak_m_z_denominator', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='peak_intensity_denominator', full_name='pb.Spectrum.peak_intensity_denominator', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='spectrum_number', full_name='pb.Spectrum.spectrum_number', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='precursor_m_z', full_name='pb.Spectrum.precursor_m_z', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rtime', full_name='pb.Spectrum.rtime', index=6,
      number=8, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='charge_state', full_name='pb.Spectrum.charge_state', index=7,
      number=7, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=23,
  serialized_end=238,
)

DESCRIPTOR.message_types_by_name['Spectrum'] = _SPECTRUM

class Spectrum(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SPECTRUM

  # @@protoc_insertion_point(class_scope:pb.Spectrum)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), 'H\001')
_SPECTRUM.fields_by_name['peak_m_z'].has_options = True
_SPECTRUM.fields_by_name['peak_m_z']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_SPECTRUM.fields_by_name['peak_intensity'].has_options = True
_SPECTRUM.fields_by_name['peak_intensity']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
_SPECTRUM.fields_by_name['charge_state'].has_options = True
_SPECTRUM.fields_by_name['charge_state']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), '\020\001')
# @@protoc_insertion_point(module_scope)
